### PR TITLE
Pseudophryne corroboree workflow

### PR DESCRIPTION
**Pull request by rvalavi**
Not enough data - only 3 records

### CODE REVIEW

**Comment by Doi90** [comment]
Has this one been re-run with the updated functions/workflow_template @rvalavi ?

**Comment by AugustHao** [comment]
there is a bunch of records from NSW data base - looks like it needs a rerun @rvalavi

**Comment by rvalavi** [comment]
This only gives me 11 records! @Doi90 @AugustHao

**Comment by Doi90** [comment]
Can you check the `spp_data$raw_data` outputs to see if anything is going wrong? There might be a lot of data in the repositories that are useless. I checked one for Darren yesterday that went from ~450 to ~70 because most were repeat visits to the same site over multiple years for example

**Comment by AugustHao** [comment]
species completed in a different branch, not needed anymore

**Pull request closed without merging**
